server:
  port: 7000
zuul:
  routes:
#    product: /abc/**

  #ignored-patterns:
  #  - /**/product/zuulTest
    abc:
      path: /cccc/**
      serviceId: product
      sensitiveHeaders:

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 172.18.34.9
    port: 5672
    username: guest
    password: guest
